### PR TITLE
Lab tests

### PR DESCRIPTION
**Pull request by tnishida1**

### CODE REVIEW

**Comment by mrparkers** [comment]
is this a WIP PR or is it meant to be merged?

**Comment by tnishida1** [comment]
meant to be merged but I don't believe I'm importing the `validate` go package correctly for the tests. I'm assuming it needs to be pushed up before I import it?

**Comment by mrparkers** [comment]
No, it shouldn't.  I only asked because there is a lot of commented code in this PR and I generally don't like committing commented code to master.  Would you be able to fix this?

**Comment by tnishida1** [comment]
Sure I removed the comments out, and I was able to import the package correctly now

**Review by mrparkers — APPROVED** [review]

**Pull request merged**
